In [19]:
pip install pandas

     |████████████████████████████████| 11.5 MB 149 kB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [20]:
import pandas as pd
import numpy as np

In [21]:
cd /home/student/Downloads/ds/review_polarity/review

/home/student/Downloads/ds/review_polarity/review


In [22]:
from os import listdir

neg=[]
mypath = r'neg/'
for f in listdir(mypath):
    neg.append(f)
    
pos=[]
mypath = r'pos/'
for f in listdir(mypath):
    pos.append(f)

In [23]:
len(neg),len(pos)

(1000, 1000)

In [24]:
negative_review=[]
for filename in neg:
    my_file = open('neg/'+filename, "r")
    content = my_file.read()
    negative_review.append(content)

In [25]:
positive_review=[]
for filename in pos:
    my_file = open('pos/'+filename, "r")
    content = my_file.read()
    positive_review.append(content)

In [26]:
neg_label=[]
pos_label=[]
for i in range(0,1000):
    neg_label.append(0)
    pos_label.append(1)

In [27]:
len(negative_review),len(neg_label),len(positive_review),len(pos_label)

(1000, 1000, 1000, 1000)

In [28]:
neg_review_data = pd.DataFrame()
neg_review_data['Review'] = negative_review.copy()
neg_review_data['label'] = neg_label.copy()

In [29]:
neg_review_data.head()

Review  label
0  it's not a bad thing to update old stories . \...      0
1  to sum the entire film " 54 " up in one senten...      0
2  despite its exceedingly well-done visual effec...      0
3  words i thought i'd never write : the sequel t...      0
4  there have been merchant-ivory costume dramas ...      0

In [30]:
pos_review_data = pd.DataFrame()
pos_review_data['Review'] = positive_review.copy()
pos_review_data['label'] = pos_label.copy()

In [31]:
pos_review_data.head()

Review  label
0  the makers of jurassic park & the director of ...      1
1  you've got to think twice before you go see a ...      1
2  i wish i could say that there is something mor...      1
3   " i'd rather die today and go to heaven than ...      1
4   " remember what the mpaa says : horrific and ...      1

In [32]:
dataframes = [pos_review_data,neg_review_data]
dataset = pd.concat(dataframes)

In [33]:
dataset.shape

(2000, 2)

In [34]:
dataset.head()

Review  label
0  the makers of jurassic park & the director of ...      1
1  you've got to think twice before you go see a ...      1
2  i wish i could say that there is something mor...      1
3   " i'd rather die today and go to heaven than ...      1
4   " remember what the mpaa says : horrific and ...      1

In [35]:
df = dataset.sample(frac = 1)

In [36]:
df = df.reset_index()

In [37]:
df = df.drop('index',axis=1)

In [38]:
df

Review  label
0     the first in a very long list of things wrong ...      0
1     just in time for halloween and christmas , the...      1
2     i tried hard not like this movie without succe...      1
3     this film is worth seeing for those who want t...      0
4     in tim burton's `sleepy hollow' , there is a m...      1
...                                                 ...    ...
1995  renowned hong kong action director tsui hark f...      0
1996  martin scorsese's kundun , which chronicles ro...      1
1997  eric rohmer's " pauline at the beach , " is on...      1
1998  ever watch a very young child try and tell a j...      0
1999  synopsis : shrek ( myers ) is an ogre living i...      1

[2000 rows x 2 columns]

In [40]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [42]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re
import nltk
nltk.download('stopwords')
from tqdm import tqdm

ps=PorterStemmer()

data_lst=[]
for text in tqdm(df['Review'],desc="Cleaning Data "):
    text=text.lower()
    text=re.sub('[^A-Za-z]',' ',text)
    text = text.split()
    text=[ps.stem(word) for word in text if word not in set(stopwords.words('english'))]
    text=' '.join(text)
    data_lst.append(text)

clean_data=pd.DataFrame(data_lst)
df['review']=clean_data

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/student/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
Cleaning Data : 100%|███████████████████████| 2000/2000 [01:44<00:00, 19.20it/s]


In [43]:
reviews=df['Review'].values
label=df['label'].values

In [45]:
pip install textblob

     |████████████████████████████████| 636 kB 678 kB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


## Using TextBlob

In [46]:
import textblob
polarity_list=[]
for review,sentiment in zip(reviews,label):
    polarity=textblob.TextBlob(review).sentiment.polarity
    print(f"Polarity of \n {review} \n is : {polarity}")
    polarity_list.append(polarity)

Polarity of 
 the first in a very long list of things wrong with " i still know what you did last summer " is the title . 
think about it for a second . 
if the last movie was called " i know what you did last summer " , wouldn't the next movie have to be " i still know what you did two summers ago " ? 
if anyone working on this movie had an i . q . 
greater than five would have thought about it logically and said , " hey . . . 
wait a minute " . 
but alas , the people behind this film are obviously idiots , so i won't hold them to that . 
what i will hold them to is the fact that they have a pretty bad movie on their hands , even for a teenage slasher flick . 
i guess i'm one of the few critics who actually kind of liked the original film ( emphasis on the " kind of " ) . 
it wasn't great or anything and maybe not even necessarily good , but at least it didn't have me glancing at my watch every minute or so like it's sequel did . 
there are just so many problems with this movie that i

Polarity of 
 star wars : episode 1 - the phantom menace ( 1999 ) 
review by matt pusateri 
few movies evoke nostalgia , enthusiasm , and affection like george lucas' 1977 classic , star wars . 
the original blockbuster film and its two sequels not only evoked wonder and passion in a generation of filmgoers , but has deeply entrenched itself in american pop culture . 
arguably , more americans today can explain what " the force " or a " jedi " is than a budget deficit or a serb . 
so 22 years after the release of the original , and 16 years since the third film , the return of the jedi , how can any new star wars film withstand the weight of incomparable expectations and anticipation ? 
can a new storyline and a new cast of characters possibly compete with the legends of the first trilogy - luke , han solo , and darth vader -all cultural icons ? 
against this challenge , the fourth star wars film , episode one : the phantom menace hit the screens last week . 
and despite some early cri

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Polarity of 
but it doesn't really make much of a difference . 
deep impact begins the official summer movie season , and it also brings back memories of 1997 . 
remember when dante's peak came out in february ? 
a few months later , volcano was released . 
the first film was smart , exhilirating , and one of the best disaster films i had ever seen . 
the latter film was an incohesive mess that defied logic and wasted talent . 
well , it's deja vu all over again as two disaster films go head to head in competition . 
this time , unfortunately , the first comet flick is so bad that people may shy away from armageddon , the upcoming comet-disaster to be released the beginning of july . 
of course , the general reaction of the audience was oppposed to mine , and so i am in the minority , as i was when i stood on the side of dante's peak . 
but while watching deep impact , i began to wonder how anyone in their right mind could actually like this film . 
apparently many did , and it utterly

In [47]:
pred_label=[1 if score>=0 else 0 for score in polarity_list]
len(pred_label),len(label)

(2000, 2000)

In [48]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(label,pred_label))
print(confusion_matrix(label,pred_label))
print(classification_report(label,pred_label))

0.6
[[229 771]
 [ 29 971]]
              precision    recall  f1-score   support

           0       0.89      0.23      0.36      1000
           1       0.56      0.97      0.71      1000

    accuracy                           0.60      2000
   macro avg       0.72      0.60      0.54      2000
weighted avg       0.72      0.60      0.54      2000



### Testing

In [49]:
test_review = 'This movie was really very bad!'
polarity=textblob.TextBlob(test_review).sentiment.polarity
if polarity>=0:
    print("You gave a POSTIVE review! Thank You.")
else:
    print("Review is not so good! Sorry.")

Review is not so good! Sorry.


# Using BOW

In [50]:
new_data=pd.DataFrame()
new_data['reviews']=reviews
new_data['sentiments']=label
new_data.head()

reviews  sentiments
0  the first in a very long list of things wrong ...           0
1  just in time for halloween and christmas , the...           1
2  i tried hard not like this movie without succe...           1
3  this film is worth seeing for those who want t...           0
4  in tim burton's `sleepy hollow' , there is a m...           1

In [56]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
cv_train=cv.fit_transform(new_data['reviews'])
cv_train

<2000x39659 sparse matrix of type '<class 'numpy.int64'>'
	with 666842 stored elements in Compressed Sparse Row format>

In [57]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(cv_train,new_data['sentiments'],test_size=0.25,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1500, 39659), (500, 39659), (1500,), (500,))

In [60]:
model=RandomForestClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [61]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.802
[[215  51]
 [ 48 186]]
              precision    recall  f1-score   support

           0       0.82      0.81      0.81       266
           1       0.78      0.79      0.79       234

    accuracy                           0.80       500
   macro avg       0.80      0.80      0.80       500
weighted avg       0.80      0.80      0.80       500



## Using TfIdfVector

In [62]:
new_data=pd.DataFrame()
new_data['reviews']=reviews
new_data['sentiments']=label
new_data.head()

reviews  sentiments
0  the first in a very long list of things wrong ...           0
1  just in time for halloween and christmas , the...           1
2  i tried hard not like this movie without succe...           1
3  this film is worth seeing for those who want t...           0
4  in tim burton's `sleepy hollow' , there is a m...           1

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
tf_train=tf.fit_transform(new_data['reviews'])

In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(tf_train,new_data['sentiments'],test_size=0.25,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1500, 39659), (500, 39659), (1500,), (500,))

## RandomForest

In [65]:
model=RandomForestClassifier()
model.fit(x_train,y_train)
tf_y_pred=model.predict(x_test)
print(accuracy_score(y_test,tf_y_pred))
print(confusion_matrix(y_test,tf_y_pred))
print(classification_report(y_test,tf_y_pred))

0.782
[[222  44]
 [ 65 169]]
              precision    recall  f1-score   support

           0       0.77      0.83      0.80       266
           1       0.79      0.72      0.76       234

    accuracy                           0.78       500
   macro avg       0.78      0.78      0.78       500
weighted avg       0.78      0.78      0.78       500



## Using HyperParameter Tuning - ADABOOST

In [66]:
from sklearn.model_selection import GridSearchCV
params={'n_estimators':[100,130,150],
        'max_features':['auto','sqrt'],
         'n_jobs':[-1,1]}
model=RandomForestClassifier()

grid=GridSearchCV(model,param_grid=params,cv=5)
grid.fit(x_train,y_train)
print(grid.best_score_)
grid.best_params_

0.792


{'max_features': 'auto', 'n_estimators': 150, 'n_jobs': -1}

## Adaboost

In [67]:
from sklearn.ensemble import AdaBoostClassifier
ada_model=AdaBoostClassifier()
ada_model.fit(x_train,y_train)
tf_y_pred=ada_model.predict(x_test)
print(accuracy_score(y_test,tf_y_pred))
print(confusion_matrix(y_test,tf_y_pred))
print(classification_report(y_test,tf_y_pred))

0.792
[[209  57]
 [ 47 187]]
              precision    recall  f1-score   support

           0       0.82      0.79      0.80       266
           1       0.77      0.80      0.78       234

    accuracy                           0.79       500
   macro avg       0.79      0.79      0.79       500
weighted avg       0.79      0.79      0.79       500



## Using HyperParameter Tuning - ADABOOST

In [ ]:
from sklearn.model_selection import GridSearchCV
params={'n_estimators':[50,70,90,110],
        'learning_rate':[0.3,0.5,0.8,1.0]}
ada_model=AdaBoostClassifier()

grid=GridSearchCV(ada_model,param_grid=params,cv=5)
grid.fit(x_train,y_train)
print(grid.best_score_)
grid.best_params_

# Testing

In [ ]:
test_review = ['movie was bad']
test=tf.transform(test_review)
test

In [ ]:
test_pred=ada_model.predict(test)
if test_pred[0]==1:
    print("You gave a POSTIVE review! Thank You.")
else:
    print("Review is not so good! Sorry.")